networks:
  traefikproxy:
    external: true

services:
  traefik:
    container_name: traefik
    image: traefik:v3.0
    restart: unless-stopped
    labels:
      - traefik.enable=true                                         # enable traefik proxying for this container
      - traefik.http.routers.api.rule=Host(`traefik.example.com`)   # Define host for this traefik dashboard
      - traefik.http.routers.api.service=api@internal               # Enable Traefik API.
    networks:
      - traefikproxy
    ports:
      - 80:80       # absolutely required
      - 443:443     # absolutely required
      - 8080:8080   # optional, webUI & metrics
    environment:
      - TZ=Europe/Berlin     # timezone
    ### run with different user/group ID
    # - PUID=1000
    # - PGID=1000
    ### required for Lets Encrypt DNS challenge auth, in this example with www.desec.io
      - DESEC_TOKEN=ABCDEFG
    command:
      - --entryPoints.http.address=:80
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik/dynamic-config.yml
    ### optional, if you want log entries to be timestamped in your actual timezone instead of default UTC
      - --accesslog.fields.names.StartUTC=drop
    ### Only required if you want to provide metrics for Prometheus
    # - --metrics 
    # - --metrics=true
    # - --metrics.prometheus=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/logs
      - ./required/traefik.yml:/etc/traefik/traefik.yml
      - ./required/fileConfig.yml:/etc/traefik/fileConfig.yml
      - ./required/acme.json:/etc/traefik/acme.json
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost:8080 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3

