networks:
  traefikproxy:
    external: true

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefikproxy
      - traefik.http.routers.homepage.rule=Host(`homepage.example.com`)           # change this to fit your domain
      - traefik.http.services.homepage.loadbalancer.server.port=3000              # the internal port of the proxy-target
    # - traefik.http.services.homepage.loadbalancer.server.scheme=https           # only when proxy-target is HTTPS
    networks:
      - traefikproxy
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./config:/app/config
