version: "3.3"

networks:
  traefikproxy:
    external: true

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefikproxy
      - traefik.http.routers.homepage.rule=Host(`homepage.example.com`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000
    ports:
      - 3333:3000
    networks:
      - traefikproxy
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./config:/app/config
